create table if not exists knowledge_articles (
  id bigint generated by default as identity primary key,
  title text not null, summary text not null, content text not null,
  tags jsonb not null default '[]'::jsonb, source_text text,
  status text not null default 'published', created_at timestamptz not null default now()
);
create table if not exists search_logs (
  id bigint generated by default as identity primary key,
  query text not null, result_count integer not null default 0,
  created_at timestamptz not null default now()
);
insert into knowledge_articles(title,summary,content,tags,source_text)
select 'VAT Returns Before Trading Begins','A company may still have VAT filing obligations before it begins trading.','VAT obligations can arise from the company's VAT registration effective date and filing cycle, not simply from the date it begins trading. If there was no taxable activity during the period, a nil return may be appropriate. Confirm the registration date and period with HMRC.',['VAT filing','VAT returns','nil return'],'If a company asks if they need to file VAT even if they have not started trading yet, the answer is yes. VAT is based on date of incorporation, not date of trading start. If no activity, it can just be filed as 0.00.'
where not exists (select 1 from knowledge_articles where title='VAT Returns Before Trading Begins');
