const base=process.env.SUPABASE_URL;
const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
const adminSecret=process.env.ADMIN_SECRET;
const headers={apikey:serviceKey,Authorization:"Bearer "+serviceKey,"Content-Type":"application/json"};
const reply=(status,body)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const terms=s=>(s||"").toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/ +/).filter(w=>w.length>2&&!"the and for with that this have from does need even they their into client".split(" ").includes(w)).map(w=>w.replace(/ing$|ed$|s$/,""));
const relevance=(article,q)=>{const text=[article.title,article.summary,article.content,...(article.tags||[])].join(" ").toLowerCase();return terms(q).reduce((n,w)=>n+(text.includes(w)?1:0),0)};
const recordSearch=async(query,resultsCount)=>{if(!query.trim())return;try{await fetch(base+"/rest/v1/search_logs",{method:"POST",headers,body:JSON.stringify({query:query.trim(),results_count:resultsCount})})}catch{}};
function makeDraft(text){const lower=text.toLowerCase();const vat=lower.includes("vat"),ico=lower.includes("ico");if(vat)return {title:"VAT Returns Before Trading Begins",summary:"VAT filing obligations may arise before trading begins.",content:"VAT obligations can arise from the VAT registration effective date and filing cycle, not simply from the date a company starts trading. If there was no taxable activity during the period, a nil return may be appropriate. Confirm the registration date and period with HMRC.",tags:["VAT filing","VAT returns","nil return"],source_text:text,status:"published"};if(ico)return {title:"ICO Registration Requirements",summary:"ICO registration depends on data-processing activity.",content:"Whether a business must pay the ICO data-protection fee depends on its activities and how it processes personal data. Check the ICO self-assessment on ico.org.uk before advising.",tags:["ICO registration","data protection"],source_text:text,status:"published"};return {title:"Knowledge Desk Note",summary:text.slice(0,190),content:text,tags:[],source_text:text,status:"published"}}
export default async req=>{try{const action=new URL(req.url).searchParams.get("action");if(req.method==="GET"){const r=await fetch(base+"/rest/v1/knowledge_articles?status=eq.published",{headers});const all=await r.json();if(action==="articles")return reply(200,all);if(action==="search"){const q=new URL(req.url).searchParams.get("q")||"";const out=all.map(a=>({...a,_score:relevance(a,q)})).filter(a=>a._score>0).sort((a,b)=>b._score-a._score);await recordSearch(q,out.length);return reply(200,out)}}if(req.method==="POST"){if(req.headers.get("x-admin-secret")!==adminSecret)return reply(401,{error:"Unauthorised"});const body=await req.json();if(body.action==="draft")return reply(200,makeDraft(body.text||""));if(body.action==="gaps"){const r=await fetch(base+"/rest/v1/search_logs?results_count=eq.0&order=created_at.desc&select=query,created_at",{headers});if(!r.ok)return reply(500,{error:"Unable to load the research queue."});const rows=await r.json(),gaps=new Map();for(const row of rows){const query=(row.query||"").trim();if(!query)continue;const item=gaps.get(query)||{query,count:0,last_seen:row.created_at};item.count+=1;if(new Date(row.created_at)>new Date(item.last_seen))item.last_seen=row.created_at;gaps.set(query,item)}return reply(200,[...gaps.values()].sort((a,b)=>b.count-a.count||new Date(b.last_seen)-new Date(a.last_seen)).slice(0,100));}if(body.action==="publish"){const r=await fetch(base+"/rest/v1/knowledge_articles",{method:"POST",headers:{...headers,Prefer:"return=representation"},body:JSON.stringify({...body.article,status:"published"})});return reply(r.status,await r.json())}}return reply(400,{error:"Invalid request"})}catch(error){return reply(500,{error:error.message})}};
